'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ws_pope_sede_sanciones
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSSancionesSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SancionDestinoPenal)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Auditoria))>  _
    Partial Public Class WSSanciones
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private VersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GrabarSancionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GrabarSancionEstadoEnviadoSedeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarSancionesPenalDestinoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GrabarSancionDestinoPenalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarPenalInicioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.APPWebService.My.MySettings.Default.APPWebService_ws_pope_sede_sanciones_WSSanciones
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event VersionCompleted As VersionCompletedEventHandler
        
        '''<remarks/>
        Public Event GrabarSancionCompleted As GrabarSancionCompletedEventHandler
        
        '''<remarks/>
        Public Event GrabarSancionEstadoEnviadoSedeCompleted As GrabarSancionEstadoEnviadoSedeCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarSancionesPenalDestinoCompleted As ListarSancionesPenalDestinoCompletedEventHandler
        
        '''<remarks/>
        Public Event GrabarSancionDestinoPenalCompleted As GrabarSancionDestinoPenalCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarPenalInicioCompleted As ListarPenalInicioCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Version() As String
            Dim results() As Object = Me.Invoke("Version", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VersionAsync()
            Me.VersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VersionAsync(ByVal userState As Object)
            If (Me.VersionOperationCompleted Is Nothing) Then
                Me.VersionOperationCompleted = AddressOf Me.OnVersionOperationCompleted
            End If
            Me.InvokeAsync("Version", New Object(-1) {}, Me.VersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.VersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VersionCompleted(Me, New VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabarSancion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GrabarSancion(ByVal objDTO As DTOVisitanteSancion) As DTOResultVisitanteSancion
            Dim results() As Object = Me.Invoke("GrabarSancion", New Object() {objDTO})
            Return CType(results(0),DTOResultVisitanteSancion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionAsync(ByVal objDTO As DTOVisitanteSancion)
            Me.GrabarSancionAsync(objDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionAsync(ByVal objDTO As DTOVisitanteSancion, ByVal userState As Object)
            If (Me.GrabarSancionOperationCompleted Is Nothing) Then
                Me.GrabarSancionOperationCompleted = AddressOf Me.OnGrabarSancionOperationCompleted
            End If
            Me.InvokeAsync("GrabarSancion", New Object() {objDTO}, Me.GrabarSancionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGrabarSancionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GrabarSancionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GrabarSancionCompleted(Me, New GrabarSancionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabarSancionEstadoEnviadoSede", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GrabarSancionEstadoEnviadoSede(ByVal objDTO As DTOVisitanteSancionEstado) As Integer
            Dim results() As Object = Me.Invoke("GrabarSancionEstadoEnviadoSede", New Object() {objDTO})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionEstadoEnviadoSedeAsync(ByVal objDTO As DTOVisitanteSancionEstado)
            Me.GrabarSancionEstadoEnviadoSedeAsync(objDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionEstadoEnviadoSedeAsync(ByVal objDTO As DTOVisitanteSancionEstado, ByVal userState As Object)
            If (Me.GrabarSancionEstadoEnviadoSedeOperationCompleted Is Nothing) Then
                Me.GrabarSancionEstadoEnviadoSedeOperationCompleted = AddressOf Me.OnGrabarSancionEstadoEnviadoSedeOperationCompleted
            End If
            Me.InvokeAsync("GrabarSancionEstadoEnviadoSede", New Object() {objDTO}, Me.GrabarSancionEstadoEnviadoSedeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGrabarSancionEstadoEnviadoSedeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GrabarSancionEstadoEnviadoSedeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GrabarSancionEstadoEnviadoSedeCompleted(Me, New GrabarSancionEstadoEnviadoSedeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSancionesPenalDestino", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarSancionesPenalDestino(ByVal objDTO As DTOSolicitud) As DTOResultSolicitud
            Dim results() As Object = Me.Invoke("ListarSancionesPenalDestino", New Object() {objDTO})
            Return CType(results(0),DTOResultSolicitud)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarSancionesPenalDestinoAsync(ByVal objDTO As DTOSolicitud)
            Me.ListarSancionesPenalDestinoAsync(objDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarSancionesPenalDestinoAsync(ByVal objDTO As DTOSolicitud, ByVal userState As Object)
            If (Me.ListarSancionesPenalDestinoOperationCompleted Is Nothing) Then
                Me.ListarSancionesPenalDestinoOperationCompleted = AddressOf Me.OnListarSancionesPenalDestinoOperationCompleted
            End If
            Me.InvokeAsync("ListarSancionesPenalDestino", New Object() {objDTO}, Me.ListarSancionesPenalDestinoOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarSancionesPenalDestinoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarSancionesPenalDestinoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarSancionesPenalDestinoCompleted(Me, New ListarSancionesPenalDestinoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabarSancionDestinoPenal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GrabarSancionDestinoPenal(ByVal objDTO As DTOSancionDestinoPenal) As Boolean
            Dim results() As Object = Me.Invoke("GrabarSancionDestinoPenal", New Object() {objDTO})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionDestinoPenalAsync(ByVal objDTO As DTOSancionDestinoPenal)
            Me.GrabarSancionDestinoPenalAsync(objDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GrabarSancionDestinoPenalAsync(ByVal objDTO As DTOSancionDestinoPenal, ByVal userState As Object)
            If (Me.GrabarSancionDestinoPenalOperationCompleted Is Nothing) Then
                Me.GrabarSancionDestinoPenalOperationCompleted = AddressOf Me.OnGrabarSancionDestinoPenalOperationCompleted
            End If
            Me.InvokeAsync("GrabarSancionDestinoPenal", New Object() {objDTO}, Me.GrabarSancionDestinoPenalOperationCompleted, userState)
        End Sub
        
        Private Sub OnGrabarSancionDestinoPenalOperationCompleted(ByVal arg As Object)
            If (Not (Me.GrabarSancionDestinoPenalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GrabarSancionDestinoPenalCompleted(Me, New GrabarSancionDestinoPenalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPenalInicio", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarPenalInicio(ByVal objDTO As DTOSolicitud) As DTOResultPenalInicio
            Dim results() As Object = Me.Invoke("ListarPenalInicio", New Object() {objDTO})
            Return CType(results(0),DTOResultPenalInicio)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarPenalInicioAsync(ByVal objDTO As DTOSolicitud)
            Me.ListarPenalInicioAsync(objDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarPenalInicioAsync(ByVal objDTO As DTOSolicitud, ByVal userState As Object)
            If (Me.ListarPenalInicioOperationCompleted Is Nothing) Then
                Me.ListarPenalInicioOperationCompleted = AddressOf Me.OnListarPenalInicioOperationCompleted
            End If
            Me.InvokeAsync("ListarPenalInicio", New Object() {objDTO}, Me.ListarPenalInicioOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarPenalInicioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarPenalInicioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarPenalInicioCompleted(Me, New ListarPenalInicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOVisitanteSancion
        
        Private visitanteField As DTOVisitante
        
        Private sancionField As DTOSancion
        
        '''<remarks/>
        Public Property Visitante() As DTOVisitante
            Get
                Return Me.visitanteField
            End Get
            Set
                Me.visitanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sancion() As DTOSancion
            Get
                Return Me.sancionField
            End Get
            Set
                Me.sancionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOVisitanteFoto)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOVisitante
        Inherits Visitante
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOVisitante)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOVisitanteFoto)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Visitante
        Inherits Auditoria
        
        Private iDVisitanteSedeField As Integer
        
        Private iDRegionOrigenField As Short
        
        Private iDPenalOrigenField As Integer
        
        Private iDVisitanteLocalField As Integer
        
        Private fechaSedeField As Long
        
        Private primerApellidoField As String
        
        Private segundoApellidoField As String
        
        Private nombresField As String
        
        Private sexoField As Short
        
        Private iDTipoDocumentoField As Short
        
        Private numeroDocumentoField As String
        
        Private fechaNacimientoField As Long
        
        Private iDNacionalidadField As Short
        
        Private observacionField As String
        
        Private fotoByteField() As Byte
        
        Private fotoNombreField As String
        
        Private iDUsuarioCapturaFotoField As Integer
        
        Private validadoReniecField As Short
        
        Private iDUsuarioValidaReniecField As Integer
        
        Private fechaValidaReniecField As Long
        
        '''<remarks/>
        Public Property IDVisitanteSede() As Integer
            Get
                Return Me.iDVisitanteSedeField
            End Get
            Set
                Me.iDVisitanteSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDRegionOrigen() As Short
            Get
                Return Me.iDRegionOrigenField
            End Get
            Set
                Me.iDRegionOrigenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenalOrigen() As Integer
            Get
                Return Me.iDPenalOrigenField
            End Get
            Set
                Me.iDPenalOrigenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDVisitanteLocal() As Integer
            Get
                Return Me.iDVisitanteLocalField
            End Get
            Set
                Me.iDVisitanteLocalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaSede() As Long
            Get
                Return Me.fechaSedeField
            End Get
            Set
                Me.fechaSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrimerApellido() As String
            Get
                Return Me.primerApellidoField
            End Get
            Set
                Me.primerApellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SegundoApellido() As String
            Get
                Return Me.segundoApellidoField
            End Get
            Set
                Me.segundoApellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombres() As String
            Get
                Return Me.nombresField
            End Get
            Set
                Me.nombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sexo() As Short
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDTipoDocumento() As Short
            Get
                Return Me.iDTipoDocumentoField
            End Get
            Set
                Me.iDTipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaNacimiento() As Long
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDNacionalidad() As Short
            Get
                Return Me.iDNacionalidadField
            End Get
            Set
                Me.iDNacionalidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Observacion() As String
            Get
                Return Me.observacionField
            End Get
            Set
                Me.observacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FotoByte() As Byte()
            Get
                Return Me.fotoByteField
            End Get
            Set
                Me.fotoByteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FotoNombre() As String
            Get
                Return Me.fotoNombreField
            End Get
            Set
                Me.fotoNombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioCapturaFoto() As Integer
            Get
                Return Me.iDUsuarioCapturaFotoField
            End Get
            Set
                Me.iDUsuarioCapturaFotoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidadoReniec() As Short
            Get
                Return Me.validadoReniecField
            End Get
            Set
                Me.validadoReniecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioValidaReniec() As Integer
            Get
                Return Me.iDUsuarioValidaReniecField
            End Get
            Set
                Me.iDUsuarioValidaReniecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaValidaReniec() As Long
            Get
                Return Me.fechaValidaReniecField
            End Get
            Set
                Me.fechaValidaReniecField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Sancion)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancion)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancionDetalle)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Visitante)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOVisitante)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOVisitanteFoto)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Auditoria
        
        Private iDUsuarioCreacionField As Integer
        
        Private fechaCreacionField As Long
        
        Private iDUsuarioModificacionField As Integer
        
        Private fechaModificacionField As Long
        
        Private iDUsuarioEliminacionField As Integer
        
        Private fechaEliminacionField As Long
        
        Private eliminadoField As Boolean
        
        '''<remarks/>
        Public Property IDUsuarioCreacion() As Integer
            Get
                Return Me.iDUsuarioCreacionField
            End Get
            Set
                Me.iDUsuarioCreacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaCreacion() As Long
            Get
                Return Me.fechaCreacionField
            End Get
            Set
                Me.fechaCreacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioModificacion() As Integer
            Get
                Return Me.iDUsuarioModificacionField
            End Get
            Set
                Me.iDUsuarioModificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaModificacion() As Long
            Get
                Return Me.fechaModificacionField
            End Get
            Set
                Me.fechaModificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioEliminacion() As Integer
            Get
                Return Me.iDUsuarioEliminacionField
            End Get
            Set
                Me.iDUsuarioEliminacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEliminacion() As Long
            Get
                Return Me.fechaEliminacionField
            End Get
            Set
                Me.fechaEliminacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Eliminado() As Boolean
            Get
                Return Me.eliminadoField
            End Get
            Set
                Me.eliminadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOResultPenalInicio
        
        Private codigoErrorField As Short
        
        Private mensajeOutField As String
        
        Private fechaInicioField As Long
        
        '''<remarks/>
        Public Property CodigoError() As Short
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeOut() As String
            Get
                Return Me.mensajeOutField
            End Get
            Set
                Me.mensajeOutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInicio() As Long
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancionDestinoPenalDetalle)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SancionDestinoPenal
        
        Private iDSancionDestinoPenalField As Integer
        
        Private iDSolicitudField As Integer
        
        Private iDSancionSedeField As Integer
        
        Private iDVisistanteSedeField As Integer
        
        Private fechaRecepcionField As Long
        
        Private estadoField As Short
        
        Private iDRegionDestinoField As Short
        
        Private iDPenalDestinoField As Short
        
        '''<remarks/>
        Public Property IDSancionDestinoPenal() As Integer
            Get
                Return Me.iDSancionDestinoPenalField
            End Get
            Set
                Me.iDSancionDestinoPenalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDSolicitud() As Integer
            Get
                Return Me.iDSolicitudField
            End Get
            Set
                Me.iDSolicitudField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDSancionSede() As Integer
            Get
                Return Me.iDSancionSedeField
            End Get
            Set
                Me.iDSancionSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDVisistanteSede() As Integer
            Get
                Return Me.iDVisistanteSedeField
            End Get
            Set
                Me.iDVisistanteSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaRecepcion() As Long
            Get
                Return Me.fechaRecepcionField
            End Get
            Set
                Me.fechaRecepcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Short
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDRegionDestino() As Short
            Get
                Return Me.iDRegionDestinoField
            End Get
            Set
                Me.iDRegionDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenalDestino() As Short
            Get
                Return Me.iDPenalDestinoField
            End Get
            Set
                Me.iDPenalDestinoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOSancionDestinoPenalDetalle
        Inherits SancionDestinoPenal
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOSancionDestinoPenal
        
        Private iDRegionField As Short
        
        Private iDPenalField As Short
        
        Private sancionDestinoPenalListaField() As DTOSancionDestinoPenalDetalle
        
        '''<remarks/>
        Public Property IDRegion() As Short
            Get
                Return Me.iDRegionField
            End Get
            Set
                Me.iDRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenal() As Short
            Get
                Return Me.iDPenalField
            End Get
            Set
                Me.iDPenalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SancionDestinoPenalLista() As DTOSancionDestinoPenalDetalle()
            Get
                Return Me.sancionDestinoPenalListaField
            End Get
            Set
                Me.sancionDestinoPenalListaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOResultSolicitud
        
        Private codigoErrorField As Short
        
        Private mensajeErrorField As String
        
        Private sancionListaField() As DTOSancionDetalle
        
        Private visitanteListaField() As DTOVisitanteFoto
        
        '''<remarks/>
        Public Property CodigoError() As Short
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SancionLista() As DTOSancionDetalle()
            Get
                Return Me.sancionListaField
            End Get
            Set
                Me.sancionListaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VisitanteLista() As DTOVisitanteFoto()
            Get
                Return Me.visitanteListaField
            End Get
            Set
                Me.visitanteListaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOSancionDetalle
        Inherits DTOSancion
        
        Private iDSolicitudDetalleField As Integer
        
        Private iDSolicitudField As Integer
        
        '''<remarks/>
        Public Property IDSolicitudDetalle() As Integer
            Get
                Return Me.iDSolicitudDetalleField
            End Get
            Set
                Me.iDSolicitudDetalleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDSolicitud() As Integer
            Get
                Return Me.iDSolicitudField
            End Get
            Set
                Me.iDSolicitudField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancionDetalle)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOSancion
        Inherits Sancion
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancion)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DTOSancionDetalle)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Sancion
        Inherits Auditoria
        
        Private iDSancionSedeField As Integer
        
        Private iDVisitanteSedeField As Integer
        
        Private iDRegionOrigenField As Short
        
        Private iDPenalOrigenField As Short
        
        Private iDSancionLocalField As Integer
        
        Private iDVisitanteLocalField As Integer
        
        Private fechaSedeSubidaField As Long
        
        Private apellidosyNombresField As String
        
        Private documentoField As String
        
        Private fechaDocField As Long
        
        Private fechaInicioField As Long
        
        Private fechaFinField As Long
        
        Private indeterminadoField As Boolean
        
        Private iDTipoSancionField As Short
        
        Private estadoField As Short
        
        Private obsField As String
        
        Private documentoAnulacionField As String
        
        Private motivoAnulacionField As String
        
        Private fechaAnulacionField As Long
        
        Private obsAnulacionField As String
        
        Private iDUsuarioAnulacionField As Integer
        
        Private estadoTransferenciaField As Short
        
        '''<remarks/>
        Public Property IDSancionSede() As Integer
            Get
                Return Me.iDSancionSedeField
            End Get
            Set
                Me.iDSancionSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDVisitanteSede() As Integer
            Get
                Return Me.iDVisitanteSedeField
            End Get
            Set
                Me.iDVisitanteSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDRegionOrigen() As Short
            Get
                Return Me.iDRegionOrigenField
            End Get
            Set
                Me.iDRegionOrigenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenalOrigen() As Short
            Get
                Return Me.iDPenalOrigenField
            End Get
            Set
                Me.iDPenalOrigenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDSancionLocal() As Integer
            Get
                Return Me.iDSancionLocalField
            End Get
            Set
                Me.iDSancionLocalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDVisitanteLocal() As Integer
            Get
                Return Me.iDVisitanteLocalField
            End Get
            Set
                Me.iDVisitanteLocalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaSedeSubida() As Long
            Get
                Return Me.fechaSedeSubidaField
            End Get
            Set
                Me.fechaSedeSubidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidosyNombres() As String
            Get
                Return Me.apellidosyNombresField
            End Get
            Set
                Me.apellidosyNombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaDoc() As Long
            Get
                Return Me.fechaDocField
            End Get
            Set
                Me.fechaDocField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInicio() As Long
            Get
                Return Me.fechaInicioField
            End Get
            Set
                Me.fechaInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaFin() As Long
            Get
                Return Me.fechaFinField
            End Get
            Set
                Me.fechaFinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Indeterminado() As Boolean
            Get
                Return Me.indeterminadoField
            End Get
            Set
                Me.indeterminadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDTipoSancion() As Short
            Get
                Return Me.iDTipoSancionField
            End Get
            Set
                Me.iDTipoSancionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Short
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obs() As String
            Get
                Return Me.obsField
            End Get
            Set
                Me.obsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocumentoAnulacion() As String
            Get
                Return Me.documentoAnulacionField
            End Get
            Set
                Me.documentoAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotivoAnulacion() As String
            Get
                Return Me.motivoAnulacionField
            End Get
            Set
                Me.motivoAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaAnulacion() As Long
            Get
                Return Me.fechaAnulacionField
            End Get
            Set
                Me.fechaAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObsAnulacion() As String
            Get
                Return Me.obsAnulacionField
            End Get
            Set
                Me.obsAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioAnulacion() As Integer
            Get
                Return Me.iDUsuarioAnulacionField
            End Get
            Set
                Me.iDUsuarioAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstadoTransferencia() As Short
            Get
                Return Me.estadoTransferenciaField
            End Get
            Set
                Me.estadoTransferenciaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOVisitanteFoto
        Inherits DTOVisitante
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOSolicitud
        
        Private iDRegionField As Short
        
        Private iDPenalField As Short
        
        '''<remarks/>
        Public Property IDRegion() As Short
            Get
                Return Me.iDRegionField
            End Get
            Set
                Me.iDRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenal() As Short
            Get
                Return Me.iDPenalField
            End Get
            Set
                Me.iDPenalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOVisitanteSancionEstado
        
        Private iDSancionField As Integer
        
        '''<remarks/>
        Public Property IDSancion() As Integer
            Get
                Return Me.iDSancionField
            End Get
            Set
                Me.iDSancionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOResultVisitanteSancion
        
        Private codigoErrorField As Short
        
        Private mensajeErrorField As String
        
        Private iDSancionField As Integer
        
        Private iDVisitanteField As Integer
        
        Private fechaSedeField As Long
        
        '''<remarks/>
        Public Property CodigoError() As Short
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDSancion() As Integer
            Get
                Return Me.iDSancionField
            End Get
            Set
                Me.iDSancionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDVisitante() As Integer
            Get
                Return Me.iDVisitanteField
            End Get
            Set
                Me.iDVisitanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaSede() As Long
            Get
                Return Me.fechaSedeField
            End Get
            Set
                Me.fechaSedeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub VersionCompletedEventHandler(ByVal sender As Object, ByVal e As VersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GrabarSancionCompletedEventHandler(ByVal sender As Object, ByVal e As GrabarSancionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GrabarSancionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTOResultVisitanteSancion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTOResultVisitanteSancion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GrabarSancionEstadoEnviadoSedeCompletedEventHandler(ByVal sender As Object, ByVal e As GrabarSancionEstadoEnviadoSedeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GrabarSancionEstadoEnviadoSedeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarSancionesPenalDestinoCompletedEventHandler(ByVal sender As Object, ByVal e As ListarSancionesPenalDestinoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarSancionesPenalDestinoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTOResultSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTOResultSolicitud)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GrabarSancionDestinoPenalCompletedEventHandler(ByVal sender As Object, ByVal e As GrabarSancionDestinoPenalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GrabarSancionDestinoPenalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarPenalInicioCompletedEventHandler(ByVal sender As Object, ByVal e As ListarPenalInicioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarPenalInicioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTOResultPenalInicio
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTOResultPenalInicio)
            End Get
        End Property
    End Class
End Namespace
