'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ws_pope_sede_plm_Interno
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InternoSedeSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InternoSede
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getFechaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarMovIntSedeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InternoPLM_MatchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InternoPLM_SelectRowIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InternoPLM_GrabarDatosBasicosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidarSihayDatosInternoPLMOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.APPWebService.My.MySettings.Default.APPWebService_ws_pope_sede_plm_Interno_WS_InternoSede
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getFechaCompleted As getFechaCompletedEventHandler
        
        '''<remarks/>
        Public Event getVersionCompleted As getVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarMovIntSedeCompleted As ListarMovIntSedeCompletedEventHandler
        
        '''<remarks/>
        Public Event InternoPLM_MatchCompleted As InternoPLM_MatchCompletedEventHandler
        
        '''<remarks/>
        Public Event InternoPLM_SelectRowIDCompleted As InternoPLM_SelectRowIDCompletedEventHandler
        
        '''<remarks/>
        Public Event InternoPLM_GrabarDatosBasicosCompleted As InternoPLM_GrabarDatosBasicosCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidarSihayDatosInternoPLMCompleted As ValidarSihayDatosInternoPLMCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFecha", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFecha() As String
            Dim results() As Object = Me.Invoke("getFecha", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFechaAsync()
            Me.getFechaAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFechaAsync(ByVal userState As Object)
            If (Me.getFechaOperationCompleted Is Nothing) Then
                Me.getFechaOperationCompleted = AddressOf Me.OngetFechaOperationCompleted
            End If
            Me.InvokeAsync("getFecha", New Object(-1) {}, Me.getFechaOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFechaOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFechaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFechaCompleted(Me, New getFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getVersion() As String
            Dim results() As Object = Me.Invoke("getVersion", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getVersionAsync()
            Me.getVersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getVersionAsync(ByVal userState As Object)
            If (Me.getVersionOperationCompleted Is Nothing) Then
                Me.getVersionOperationCompleted = AddressOf Me.OngetVersionOperationCompleted
            End If
            Me.InvokeAsync("getVersion", New Object(-1) {}, Me.getVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OngetVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.getVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getVersionCompleted(Me, New getVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarMovIntSede", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarMovIntSede(ByVal dtoInt As DTO_Interno) As DTO_ResultOfDataTable
            Dim results() As Object = Me.Invoke("ListarMovIntSede", New Object() {dtoInt})
            Return CType(results(0),DTO_ResultOfDataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarMovIntSedeAsync(ByVal dtoInt As DTO_Interno)
            Me.ListarMovIntSedeAsync(dtoInt, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarMovIntSedeAsync(ByVal dtoInt As DTO_Interno, ByVal userState As Object)
            If (Me.ListarMovIntSedeOperationCompleted Is Nothing) Then
                Me.ListarMovIntSedeOperationCompleted = AddressOf Me.OnListarMovIntSedeOperationCompleted
            End If
            Me.InvokeAsync("ListarMovIntSede", New Object() {dtoInt}, Me.ListarMovIntSedeOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarMovIntSedeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarMovIntSedeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarMovIntSedeCompleted(Me, New ListarMovIntSedeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InternoPLM_Match", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InternoPLM_Match(ByVal objDto As DTO_Interno) As DTO_ResultOfDataSet
            Dim results() As Object = Me.Invoke("InternoPLM_Match", New Object() {objDto})
            Return CType(results(0),DTO_ResultOfDataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_MatchAsync(ByVal objDto As DTO_Interno)
            Me.InternoPLM_MatchAsync(objDto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_MatchAsync(ByVal objDto As DTO_Interno, ByVal userState As Object)
            If (Me.InternoPLM_MatchOperationCompleted Is Nothing) Then
                Me.InternoPLM_MatchOperationCompleted = AddressOf Me.OnInternoPLM_MatchOperationCompleted
            End If
            Me.InvokeAsync("InternoPLM_Match", New Object() {objDto}, Me.InternoPLM_MatchOperationCompleted, userState)
        End Sub
        
        Private Sub OnInternoPLM_MatchOperationCompleted(ByVal arg As Object)
            If (Not (Me.InternoPLM_MatchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InternoPLM_MatchCompleted(Me, New InternoPLM_MatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InternoPLM_SelectRowID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InternoPLM_SelectRowID(ByVal objDto As DTO_Interno) As DTO_ResultOfDataTable
            Dim results() As Object = Me.Invoke("InternoPLM_SelectRowID", New Object() {objDto})
            Return CType(results(0),DTO_ResultOfDataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_SelectRowIDAsync(ByVal objDto As DTO_Interno)
            Me.InternoPLM_SelectRowIDAsync(objDto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_SelectRowIDAsync(ByVal objDto As DTO_Interno, ByVal userState As Object)
            If (Me.InternoPLM_SelectRowIDOperationCompleted Is Nothing) Then
                Me.InternoPLM_SelectRowIDOperationCompleted = AddressOf Me.OnInternoPLM_SelectRowIDOperationCompleted
            End If
            Me.InvokeAsync("InternoPLM_SelectRowID", New Object() {objDto}, Me.InternoPLM_SelectRowIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnInternoPLM_SelectRowIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.InternoPLM_SelectRowIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InternoPLM_SelectRowIDCompleted(Me, New InternoPLM_SelectRowIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InternoPLM_GrabarDatosBasicos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InternoPLM_GrabarDatosBasicos(ByVal objDto As DTO_Interno) As DTO_ResultOfInt64
            Dim results() As Object = Me.Invoke("InternoPLM_GrabarDatosBasicos", New Object() {objDto})
            Return CType(results(0),DTO_ResultOfInt64)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_GrabarDatosBasicosAsync(ByVal objDto As DTO_Interno)
            Me.InternoPLM_GrabarDatosBasicosAsync(objDto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InternoPLM_GrabarDatosBasicosAsync(ByVal objDto As DTO_Interno, ByVal userState As Object)
            If (Me.InternoPLM_GrabarDatosBasicosOperationCompleted Is Nothing) Then
                Me.InternoPLM_GrabarDatosBasicosOperationCompleted = AddressOf Me.OnInternoPLM_GrabarDatosBasicosOperationCompleted
            End If
            Me.InvokeAsync("InternoPLM_GrabarDatosBasicos", New Object() {objDto}, Me.InternoPLM_GrabarDatosBasicosOperationCompleted, userState)
        End Sub
        
        Private Sub OnInternoPLM_GrabarDatosBasicosOperationCompleted(ByVal arg As Object)
            If (Not (Me.InternoPLM_GrabarDatosBasicosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InternoPLM_GrabarDatosBasicosCompleted(Me, New InternoPLM_GrabarDatosBasicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarSihayDatosInternoPLM", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidarSihayDatosInternoPLM(ByVal IDInternoSede As Integer) As DTO_ResultOfBoolean
            Dim results() As Object = Me.Invoke("ValidarSihayDatosInternoPLM", New Object() {IDInternoSede})
            Return CType(results(0),DTO_ResultOfBoolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidarSihayDatosInternoPLMAsync(ByVal IDInternoSede As Integer)
            Me.ValidarSihayDatosInternoPLMAsync(IDInternoSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidarSihayDatosInternoPLMAsync(ByVal IDInternoSede As Integer, ByVal userState As Object)
            If (Me.ValidarSihayDatosInternoPLMOperationCompleted Is Nothing) Then
                Me.ValidarSihayDatosInternoPLMOperationCompleted = AddressOf Me.OnValidarSihayDatosInternoPLMOperationCompleted
            End If
            Me.InvokeAsync("ValidarSihayDatosInternoPLM", New Object() {IDInternoSede}, Me.ValidarSihayDatosInternoPLMOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidarSihayDatosInternoPLMOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidarSihayDatosInternoPLMCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidarSihayDatosInternoPLMCompleted(Me, New ValidarSihayDatosInternoPLMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_Interno
        
        Private iDInternoSedeField As Integer
        
        Private codigoRPField As String
        
        Private tipoDocumentoIDField As Short
        
        Private numeroDocumentoField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private nombresField As String
        
        Private estadoInternoField As Short
        
        Private fechaNacimientoField As Long
        
        Private iDNacionalidadField As Short
        
        Private iDPenalField As Short
        
        Private iDRegionField As Short
        
        Private iDRowField As Integer
        
        Private ingresoDtoField As DTOInternoIngreso
        
        '''<remarks/>
        Public Property IDInternoSede() As Integer
            Get
                Return Me.iDInternoSedeField
            End Get
            Set
                Me.iDInternoSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoRP() As String
            Get
                Return Me.codigoRPField
            End Get
            Set
                Me.codigoRPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoDocumentoID() As Short
            Get
                Return Me.tipoDocumentoIDField
            End Get
            Set
                Me.tipoDocumentoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombres() As String
            Get
                Return Me.nombresField
            End Get
            Set
                Me.nombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstadoInterno() As Short
            Get
                Return Me.estadoInternoField
            End Get
            Set
                Me.estadoInternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaNacimiento() As Long
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDNacionalidad() As Short
            Get
                Return Me.iDNacionalidadField
            End Get
            Set
                Me.iDNacionalidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDPenal() As Short
            Get
                Return Me.iDPenalField
            End Get
            Set
                Me.iDPenalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDRegion() As Short
            Get
                Return Me.iDRegionField
            End Get
            Set
                Me.iDRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDRow() As Integer
            Get
                Return Me.iDRowField
            End Get
            Set
                Me.iDRowField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IngresoDto() As DTOInternoIngreso
            Get
                Return Me.ingresoDtoField
            End Get
            Set
                Me.ingresoDtoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTOInternoIngreso
        
        Private iDInternoSedeField As Long
        
        Private iDIngresoLocalField As Long
        
        Private iDTipoMovimientoField As Short
        
        Private iDMovimientoMotivoField As Short
        
        Private fechaISPField As Long
        
        Private fechaIngresoField As Long
        
        Private numeroIngresoField As Short
        
        Private observacionField As String
        
        Private iDUsuarioCreacionField As Integer
        
        Private iDUsuarioModificacionField As Integer
        
        '''<remarks/>
        Public Property IDInternoSede() As Long
            Get
                Return Me.iDInternoSedeField
            End Get
            Set
                Me.iDInternoSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDIngresoLocal() As Long
            Get
                Return Me.iDIngresoLocalField
            End Get
            Set
                Me.iDIngresoLocalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDTipoMovimiento() As Short
            Get
                Return Me.iDTipoMovimientoField
            End Get
            Set
                Me.iDTipoMovimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDMovimientoMotivo() As Short
            Get
                Return Me.iDMovimientoMotivoField
            End Get
            Set
                Me.iDMovimientoMotivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaISP() As Long
            Get
                Return Me.fechaISPField
            End Get
            Set
                Me.fechaISPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaIngreso() As Long
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroIngreso() As Short
            Get
                Return Me.numeroIngresoField
            End Get
            Set
                Me.numeroIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Observacion() As String
            Get
                Return Me.observacionField
            End Get
            Set
                Me.observacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioCreacion() As Integer
            Get
                Return Me.iDUsuarioCreacionField
            End Get
            Set
                Me.iDUsuarioCreacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUsuarioModificacion() As Integer
            Get
                Return Me.iDUsuarioModificacionField
            End Get
            Set
                Me.iDUsuarioModificacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfBoolean
        
        Private resultadoField As Boolean
        
        Private error_codField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_cod() As Integer
            Get
                Return Me.error_codField
            End Get
            Set
                Me.error_codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfInt64
        
        Private resultadoField As Long
        
        Private error_codField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As Long
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_cod() As Integer
            Get
                Return Me.error_codField
            End Get
            Set
                Me.error_codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfDataSet
        
        Private resultadoField As System.Data.DataSet
        
        Private error_codField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As System.Data.DataSet
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_cod() As Integer
            Get
                Return Me.error_codField
            End Get
            Set
                Me.error_codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfDataTable
        
        Private resultadoField As System.Data.DataTable
        
        Private error_codField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As System.Data.DataTable
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_cod() As Integer
            Get
                Return Me.error_codField
            End Get
            Set
                Me.error_codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getFechaCompletedEventHandler(ByVal sender As Object, ByVal e As getFechaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFechaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getVersionCompletedEventHandler(ByVal sender As Object, ByVal e As getVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarMovIntSedeCompletedEventHandler(ByVal sender As Object, ByVal e As ListarMovIntSedeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarMovIntSedeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfDataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfDataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InternoPLM_MatchCompletedEventHandler(ByVal sender As Object, ByVal e As InternoPLM_MatchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InternoPLM_MatchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfDataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfDataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InternoPLM_SelectRowIDCompletedEventHandler(ByVal sender As Object, ByVal e As InternoPLM_SelectRowIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InternoPLM_SelectRowIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfDataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfDataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InternoPLM_GrabarDatosBasicosCompletedEventHandler(ByVal sender As Object, ByVal e As InternoPLM_GrabarDatosBasicosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InternoPLM_GrabarDatosBasicosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfInt64
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfInt64)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ValidarSihayDatosInternoPLMCompletedEventHandler(ByVal sender As Object, ByVal e As ValidarSihayDatosInternoPLMCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidarSihayDatosInternoPLMCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfBoolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfBoolean)
            End Get
        End Property
    End Class
End Namespace
