'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace ws_pope_sede_uploadfile
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoArchivo", [Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoArchivo As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ninguno = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Interno = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Personal = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Visitante = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Reniec = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Reniec_Sybase = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Odontograma = 6
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ws_pope_sede_uploadfile.UploadFileSoap")>  _
    Public Interface UploadFileSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ImagenByte del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UploadImageJpg", ReplyAction:="*")>  _
        Function UploadImageJpg(ByVal request As ws_pope_sede_uploadfile.UploadImageJpgRequest) As ws_pope_sede_uploadfile.UploadImageJpgResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UploadImageJpg", ReplyAction:="*")>  _
        Function UploadImageJpgAsync(ByVal request As ws_pope_sede_uploadfile.UploadImageJpgRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.UploadImageJpgResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MesCorrelativo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SubirArchivoByte", ReplyAction:="*")>  _
        Function SubirArchivoByte(ByVal request As ws_pope_sede_uploadfile.SubirArchivoByteRequest) As ws_pope_sede_uploadfile.SubirArchivoByteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SubirArchivoByte", ReplyAction:="*")>  _
        Function SubirArchivoByteAsync(ByVal request As ws_pope_sede_uploadfile.SubirArchivoByteRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.SubirArchivoByteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NameFile del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LeerArchivoByte", ReplyAction:="*")>  _
        Function LeerArchivoByte(ByVal request As ws_pope_sede_uploadfile.LeerArchivoByteRequest) As ws_pope_sede_uploadfile.LeerArchivoByteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LeerArchivoByte", ReplyAction:="*")>  _
        Function LeerArchivoByteAsync(ByVal request As ws_pope_sede_uploadfile.LeerArchivoByteRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.LeerArchivoByteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Asunto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarCorreo", ReplyAction:="*")>  _
        Function EnviarCorreo(ByVal request As ws_pope_sede_uploadfile.EnviarCorreoRequest) As ws_pope_sede_uploadfile.EnviarCorreoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarCorreo", ReplyAction:="*")>  _
        Function EnviarCorreoAsync(ByVal request As ws_pope_sede_uploadfile.EnviarCorreoRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.EnviarCorreoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VersionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Version", ReplyAction:="*")>  _
        Function Version(ByVal request As ws_pope_sede_uploadfile.VersionRequest) As ws_pope_sede_uploadfile.VersionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Version", ReplyAction:="*")>  _
        Function VersionAsync(ByVal request As ws_pope_sede_uploadfile.VersionRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.VersionResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento testResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/test", ReplyAction:="*")>  _
        Function test(ByVal request As ws_pope_sede_uploadfile.testRequest) As ws_pope_sede_uploadfile.testResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/test", ReplyAction:="*")>  _
        Function testAsync(ByVal request As ws_pope_sede_uploadfile.testRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.testResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadImageJpgRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadImageJpg", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.UploadImageJpgRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.UploadImageJpgRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UploadImageJpgRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ImagenByte() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NameFile As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public TipoDirectorio As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ImagenByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As Integer)
            MyBase.New
            Me.ImagenByte = ImagenByte
            Me.NameFile = NameFile
            Me.TipoDirectorio = TipoDirectorio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadImageJpgResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadImageJpgResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.UploadImageJpgResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.UploadImageJpgResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UploadImageJpgResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public UploadImageJpgResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UploadImageJpgResult As Boolean)
            MyBase.New
            Me.UploadImageJpgResult = UploadImageJpgResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubirArchivoByteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SubirArchivoByte", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.SubirArchivoByteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.SubirArchivoByteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SubirArchivoByteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public RegionID As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public PenalID As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Anio As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public MesCorrelativo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public FileByte() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public NameFile As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RegionID As Short, ByVal PenalID As Short, ByVal Anio As Short, ByVal MesCorrelativo As String, ByVal FileByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo)
            MyBase.New
            Me.RegionID = RegionID
            Me.PenalID = PenalID
            Me.Anio = Anio
            Me.MesCorrelativo = MesCorrelativo
            Me.FileByte = FileByte
            Me.NameFile = NameFile
            Me.TipoDirectorio = TipoDirectorio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubirArchivoByteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SubirArchivoByteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.SubirArchivoByteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.SubirArchivoByteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SubirArchivoByteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SubirArchivoByteResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SubirArchivoByteResult As Boolean)
            MyBase.New
            Me.SubirArchivoByteResult = SubirArchivoByteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LeerArchivoByteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LeerArchivoByte", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.LeerArchivoByteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.LeerArchivoByteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LeerArchivoByteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NameFile As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public PathWeb As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo, ByVal NameFile As String, ByVal PathWeb As String)
            MyBase.New
            Me.TipoDirectorio = TipoDirectorio
            Me.NameFile = NameFile
            Me.PathWeb = PathWeb
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LeerArchivoByteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LeerArchivoByteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.LeerArchivoByteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.LeerArchivoByteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LeerArchivoByteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LeerArchivoByteResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LeerArchivoByteResult() As Byte)
            MyBase.New
            Me.LeerArchivoByteResult = LeerArchivoByteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarCorreoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarCorreo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.EnviarCorreoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.EnviarCorreoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarCorreoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Asunto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Mensaje As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Asunto As String, ByVal Mensaje As String)
            MyBase.New
            Me.Asunto = Asunto
            Me.Mensaje = Mensaje
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarCorreoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarCorreoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.EnviarCorreoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.EnviarCorreoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarCorreoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarCorreoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarCorreoResult As Boolean)
            MyBase.New
            Me.EnviarCorreoResult = EnviarCorreoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VersionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Version", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.VersionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.VersionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class VersionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VersionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VersionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.VersionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.VersionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VersionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public VersionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VersionResult As String)
            MyBase.New
            Me.VersionResult = VersionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class testRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="test", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.testRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.testRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class testRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class testResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="testResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ws_pope_sede_uploadfile.testResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ws_pope_sede_uploadfile.testResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class testResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public testResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal testResult As String)
            MyBase.New
            Me.testResult = testResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UploadFileSoapChannel
        Inherits ws_pope_sede_uploadfile.UploadFileSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UploadFileSoapClient
        Inherits System.ServiceModel.ClientBase(Of ws_pope_sede_uploadfile.UploadFileSoap)
        Implements ws_pope_sede_uploadfile.UploadFileSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_UploadImageJpg(ByVal request As ws_pope_sede_uploadfile.UploadImageJpgRequest) As ws_pope_sede_uploadfile.UploadImageJpgResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.UploadImageJpg
            Return MyBase.Channel.UploadImageJpg(request)
        End Function
        
        Public Function UploadImageJpg(ByVal ImagenByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As Integer) As Boolean
            Dim inValue As ws_pope_sede_uploadfile.UploadImageJpgRequest = New ws_pope_sede_uploadfile.UploadImageJpgRequest()
            inValue.Body = New ws_pope_sede_uploadfile.UploadImageJpgRequestBody()
            inValue.Body.ImagenByte = ImagenByte
            inValue.Body.NameFile = NameFile
            inValue.Body.TipoDirectorio = TipoDirectorio
            Dim retVal As ws_pope_sede_uploadfile.UploadImageJpgResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).UploadImageJpg(inValue)
            Return retVal.Body.UploadImageJpgResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_UploadImageJpgAsync(ByVal request As ws_pope_sede_uploadfile.UploadImageJpgRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.UploadImageJpgResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.UploadImageJpgAsync
            Return MyBase.Channel.UploadImageJpgAsync(request)
        End Function
        
        Public Function UploadImageJpgAsync(ByVal ImagenByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As Integer) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.UploadImageJpgResponse)
            Dim inValue As ws_pope_sede_uploadfile.UploadImageJpgRequest = New ws_pope_sede_uploadfile.UploadImageJpgRequest()
            inValue.Body = New ws_pope_sede_uploadfile.UploadImageJpgRequestBody()
            inValue.Body.ImagenByte = ImagenByte
            inValue.Body.NameFile = NameFile
            inValue.Body.TipoDirectorio = TipoDirectorio
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).UploadImageJpgAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_SubirArchivoByte(ByVal request As ws_pope_sede_uploadfile.SubirArchivoByteRequest) As ws_pope_sede_uploadfile.SubirArchivoByteResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.SubirArchivoByte
            Return MyBase.Channel.SubirArchivoByte(request)
        End Function
        
        Public Function SubirArchivoByte(ByVal RegionID As Short, ByVal PenalID As Short, ByVal Anio As Short, ByVal MesCorrelativo As String, ByVal FileByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo) As Boolean
            Dim inValue As ws_pope_sede_uploadfile.SubirArchivoByteRequest = New ws_pope_sede_uploadfile.SubirArchivoByteRequest()
            inValue.Body = New ws_pope_sede_uploadfile.SubirArchivoByteRequestBody()
            inValue.Body.RegionID = RegionID
            inValue.Body.PenalID = PenalID
            inValue.Body.Anio = Anio
            inValue.Body.MesCorrelativo = MesCorrelativo
            inValue.Body.FileByte = FileByte
            inValue.Body.NameFile = NameFile
            inValue.Body.TipoDirectorio = TipoDirectorio
            Dim retVal As ws_pope_sede_uploadfile.SubirArchivoByteResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).SubirArchivoByte(inValue)
            Return retVal.Body.SubirArchivoByteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_SubirArchivoByteAsync(ByVal request As ws_pope_sede_uploadfile.SubirArchivoByteRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.SubirArchivoByteResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.SubirArchivoByteAsync
            Return MyBase.Channel.SubirArchivoByteAsync(request)
        End Function
        
        Public Function SubirArchivoByteAsync(ByVal RegionID As Short, ByVal PenalID As Short, ByVal Anio As Short, ByVal MesCorrelativo As String, ByVal FileByte() As Byte, ByVal NameFile As String, ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.SubirArchivoByteResponse)
            Dim inValue As ws_pope_sede_uploadfile.SubirArchivoByteRequest = New ws_pope_sede_uploadfile.SubirArchivoByteRequest()
            inValue.Body = New ws_pope_sede_uploadfile.SubirArchivoByteRequestBody()
            inValue.Body.RegionID = RegionID
            inValue.Body.PenalID = PenalID
            inValue.Body.Anio = Anio
            inValue.Body.MesCorrelativo = MesCorrelativo
            inValue.Body.FileByte = FileByte
            inValue.Body.NameFile = NameFile
            inValue.Body.TipoDirectorio = TipoDirectorio
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).SubirArchivoByteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_LeerArchivoByte(ByVal request As ws_pope_sede_uploadfile.LeerArchivoByteRequest) As ws_pope_sede_uploadfile.LeerArchivoByteResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.LeerArchivoByte
            Return MyBase.Channel.LeerArchivoByte(request)
        End Function
        
        Public Function LeerArchivoByte(ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo, ByVal NameFile As String, ByVal PathWeb As String) As Byte()
            Dim inValue As ws_pope_sede_uploadfile.LeerArchivoByteRequest = New ws_pope_sede_uploadfile.LeerArchivoByteRequest()
            inValue.Body = New ws_pope_sede_uploadfile.LeerArchivoByteRequestBody()
            inValue.Body.TipoDirectorio = TipoDirectorio
            inValue.Body.NameFile = NameFile
            inValue.Body.PathWeb = PathWeb
            Dim retVal As ws_pope_sede_uploadfile.LeerArchivoByteResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).LeerArchivoByte(inValue)
            Return retVal.Body.LeerArchivoByteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_LeerArchivoByteAsync(ByVal request As ws_pope_sede_uploadfile.LeerArchivoByteRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.LeerArchivoByteResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.LeerArchivoByteAsync
            Return MyBase.Channel.LeerArchivoByteAsync(request)
        End Function
        
        Public Function LeerArchivoByteAsync(ByVal TipoDirectorio As ws_pope_sede_uploadfile.TipoArchivo, ByVal NameFile As String, ByVal PathWeb As String) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.LeerArchivoByteResponse)
            Dim inValue As ws_pope_sede_uploadfile.LeerArchivoByteRequest = New ws_pope_sede_uploadfile.LeerArchivoByteRequest()
            inValue.Body = New ws_pope_sede_uploadfile.LeerArchivoByteRequestBody()
            inValue.Body.TipoDirectorio = TipoDirectorio
            inValue.Body.NameFile = NameFile
            inValue.Body.PathWeb = PathWeb
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).LeerArchivoByteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_EnviarCorreo(ByVal request As ws_pope_sede_uploadfile.EnviarCorreoRequest) As ws_pope_sede_uploadfile.EnviarCorreoResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.EnviarCorreo
            Return MyBase.Channel.EnviarCorreo(request)
        End Function
        
        Public Function EnviarCorreo(ByVal Asunto As String, ByVal Mensaje As String) As Boolean
            Dim inValue As ws_pope_sede_uploadfile.EnviarCorreoRequest = New ws_pope_sede_uploadfile.EnviarCorreoRequest()
            inValue.Body = New ws_pope_sede_uploadfile.EnviarCorreoRequestBody()
            inValue.Body.Asunto = Asunto
            inValue.Body.Mensaje = Mensaje
            Dim retVal As ws_pope_sede_uploadfile.EnviarCorreoResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).EnviarCorreo(inValue)
            Return retVal.Body.EnviarCorreoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_EnviarCorreoAsync(ByVal request As ws_pope_sede_uploadfile.EnviarCorreoRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.EnviarCorreoResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.EnviarCorreoAsync
            Return MyBase.Channel.EnviarCorreoAsync(request)
        End Function
        
        Public Function EnviarCorreoAsync(ByVal Asunto As String, ByVal Mensaje As String) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.EnviarCorreoResponse)
            Dim inValue As ws_pope_sede_uploadfile.EnviarCorreoRequest = New ws_pope_sede_uploadfile.EnviarCorreoRequest()
            inValue.Body = New ws_pope_sede_uploadfile.EnviarCorreoRequestBody()
            inValue.Body.Asunto = Asunto
            inValue.Body.Mensaje = Mensaje
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).EnviarCorreoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_Version(ByVal request As ws_pope_sede_uploadfile.VersionRequest) As ws_pope_sede_uploadfile.VersionResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.Version
            Return MyBase.Channel.Version(request)
        End Function
        
        Public Function Version() As String
            Dim inValue As ws_pope_sede_uploadfile.VersionRequest = New ws_pope_sede_uploadfile.VersionRequest()
            inValue.Body = New ws_pope_sede_uploadfile.VersionRequestBody()
            Dim retVal As ws_pope_sede_uploadfile.VersionResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).Version(inValue)
            Return retVal.Body.VersionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_VersionAsync(ByVal request As ws_pope_sede_uploadfile.VersionRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.VersionResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.VersionAsync
            Return MyBase.Channel.VersionAsync(request)
        End Function
        
        Public Function VersionAsync() As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.VersionResponse)
            Dim inValue As ws_pope_sede_uploadfile.VersionRequest = New ws_pope_sede_uploadfile.VersionRequest()
            inValue.Body = New ws_pope_sede_uploadfile.VersionRequestBody()
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).VersionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_test(ByVal request As ws_pope_sede_uploadfile.testRequest) As ws_pope_sede_uploadfile.testResponse Implements ws_pope_sede_uploadfile.UploadFileSoap.test
            Return MyBase.Channel.test(request)
        End Function
        
        Public Function test() As String
            Dim inValue As ws_pope_sede_uploadfile.testRequest = New ws_pope_sede_uploadfile.testRequest()
            inValue.Body = New ws_pope_sede_uploadfile.testRequestBody()
            Dim retVal As ws_pope_sede_uploadfile.testResponse = CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).test(inValue)
            Return retVal.Body.testResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ws_pope_sede_uploadfile_UploadFileSoap_testAsync(ByVal request As ws_pope_sede_uploadfile.testRequest) As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.testResponse) Implements ws_pope_sede_uploadfile.UploadFileSoap.testAsync
            Return MyBase.Channel.testAsync(request)
        End Function
        
        Public Function testAsync() As System.Threading.Tasks.Task(Of ws_pope_sede_uploadfile.testResponse)
            Dim inValue As ws_pope_sede_uploadfile.testRequest = New ws_pope_sede_uploadfile.testRequest()
            inValue.Body = New ws_pope_sede_uploadfile.testRequestBody()
            Return CType(Me,ws_pope_sede_uploadfile.UploadFileSoap).testAsync(inValue)
        End Function
    End Class
End Namespace
