'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ws_reniec_sede
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IdentificacionSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Identificacion
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private VersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FechaLongOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SolicitudOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Solicitud_LeerDNIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Solicitud_LeerApellidosyNombresOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.APPWebService.My.MySettings.Default.APPWebService_ws_reniec_sede_Identificacion
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event VersionCompleted As VersionCompletedEventHandler
        
        '''<remarks/>
        Public Event FechaLongCompleted As FechaLongCompletedEventHandler
        
        '''<remarks/>
        Public Event SolicitudCompleted As SolicitudCompletedEventHandler
        
        '''<remarks/>
        Public Event Solicitud_LeerDNICompleted As Solicitud_LeerDNICompletedEventHandler
        
        '''<remarks/>
        Public Event Solicitud_LeerApellidosyNombresCompleted As Solicitud_LeerApellidosyNombresCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Version() As String
            Dim results() As Object = Me.Invoke("Version", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VersionAsync()
            Me.VersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VersionAsync(ByVal userState As Object)
            If (Me.VersionOperationCompleted Is Nothing) Then
                Me.VersionOperationCompleted = AddressOf Me.OnVersionOperationCompleted
            End If
            Me.InvokeAsync("Version", New Object(-1) {}, Me.VersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.VersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VersionCompleted(Me, New VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechaLong", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FechaLong() As Long
            Dim results() As Object = Me.Invoke("FechaLong", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FechaLongAsync()
            Me.FechaLongAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FechaLongAsync(ByVal userState As Object)
            If (Me.FechaLongOperationCompleted Is Nothing) Then
                Me.FechaLongOperationCompleted = AddressOf Me.OnFechaLongOperationCompleted
            End If
            Me.InvokeAsync("FechaLong", New Object(-1) {}, Me.FechaLongOperationCompleted, userState)
        End Sub
        
        Private Sub OnFechaLongOperationCompleted(ByVal arg As Object)
            If (Not (Me.FechaLongCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FechaLongCompleted(Me, New FechaLongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Solicitud", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Solicitud(ByVal obj As EscribirCola) As DTO_ResultOfRespuesta
            Dim results() As Object = Me.Invoke("Solicitud", New Object() {obj})
            Return CType(results(0),DTO_ResultOfRespuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SolicitudAsync(ByVal obj As EscribirCola)
            Me.SolicitudAsync(obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SolicitudAsync(ByVal obj As EscribirCola, ByVal userState As Object)
            If (Me.SolicitudOperationCompleted Is Nothing) Then
                Me.SolicitudOperationCompleted = AddressOf Me.OnSolicitudOperationCompleted
            End If
            Me.InvokeAsync("Solicitud", New Object() {obj}, Me.SolicitudOperationCompleted, userState)
        End Sub
        
        Private Sub OnSolicitudOperationCompleted(ByVal arg As Object)
            If (Not (Me.SolicitudCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SolicitudCompleted(Me, New SolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Solicitud_LeerDNI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Solicitud_LeerDNI(ByVal obj As LeerCola) As DTO_ResultOfNumeroDocumento
            Dim results() As Object = Me.Invoke("Solicitud_LeerDNI", New Object() {obj})
            Return CType(results(0),DTO_ResultOfNumeroDocumento)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Solicitud_LeerDNIAsync(ByVal obj As LeerCola)
            Me.Solicitud_LeerDNIAsync(obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Solicitud_LeerDNIAsync(ByVal obj As LeerCola, ByVal userState As Object)
            If (Me.Solicitud_LeerDNIOperationCompleted Is Nothing) Then
                Me.Solicitud_LeerDNIOperationCompleted = AddressOf Me.OnSolicitud_LeerDNIOperationCompleted
            End If
            Me.InvokeAsync("Solicitud_LeerDNI", New Object() {obj}, Me.Solicitud_LeerDNIOperationCompleted, userState)
        End Sub
        
        Private Sub OnSolicitud_LeerDNIOperationCompleted(ByVal arg As Object)
            If (Not (Me.Solicitud_LeerDNICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Solicitud_LeerDNICompleted(Me, New Solicitud_LeerDNICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Solicitud_LeerApellidosyNombres", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Solicitud_LeerApellidosyNombres(ByVal obj As LeerCola) As DTO_ResultOfApellidosyNombres
            Dim results() As Object = Me.Invoke("Solicitud_LeerApellidosyNombres", New Object() {obj})
            Return CType(results(0),DTO_ResultOfApellidosyNombres)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Solicitud_LeerApellidosyNombresAsync(ByVal obj As LeerCola)
            Me.Solicitud_LeerApellidosyNombresAsync(obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Solicitud_LeerApellidosyNombresAsync(ByVal obj As LeerCola, ByVal userState As Object)
            If (Me.Solicitud_LeerApellidosyNombresOperationCompleted Is Nothing) Then
                Me.Solicitud_LeerApellidosyNombresOperationCompleted = AddressOf Me.OnSolicitud_LeerApellidosyNombresOperationCompleted
            End If
            Me.InvokeAsync("Solicitud_LeerApellidosyNombres", New Object() {obj}, Me.Solicitud_LeerApellidosyNombresOperationCompleted, userState)
        End Sub
        
        Private Sub OnSolicitud_LeerApellidosyNombresOperationCompleted(ByVal arg As Object)
            If (Not (Me.Solicitud_LeerApellidosyNombresCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Solicitud_LeerApellidosyNombresCompleted(Me, New Solicitud_LeerApellidosyNombresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EscribirCola
        
        Private tipoConsultaField As Integer
        
        Private consultaNumeroDNIField As String
        
        Private consultaPrimerApellidoField As String
        
        Private consultaSegundoApellidoField As String
        
        Private consultaPreNombresField As String
        
        Private loginField As String
        
        Private mACField As String
        
        Private ipField As String
        
        Private keySistemaField As String
        
        Private claveSistemaField As String
        
        Private iDModuloField As Integer
        
        '''<remarks/>
        Public Property TipoConsulta() As Integer
            Get
                Return Me.tipoConsultaField
            End Get
            Set
                Me.tipoConsultaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsultaNumeroDNI() As String
            Get
                Return Me.consultaNumeroDNIField
            End Get
            Set
                Me.consultaNumeroDNIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsultaPrimerApellido() As String
            Get
                Return Me.consultaPrimerApellidoField
            End Get
            Set
                Me.consultaPrimerApellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsultaSegundoApellido() As String
            Get
                Return Me.consultaSegundoApellidoField
            End Get
            Set
                Me.consultaSegundoApellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsultaPreNombres() As String
            Get
                Return Me.consultaPreNombresField
            End Get
            Set
                Me.consultaPreNombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Login() As String
            Get
                Return Me.loginField
            End Get
            Set
                Me.loginField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MAC() As String
            Get
                Return Me.mACField
            End Get
            Set
                Me.mACField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IP() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property KeySistema() As String
            Get
                Return Me.keySistemaField
            End Get
            Set
                Me.keySistemaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveSistema() As String
            Get
                Return Me.claveSistemaField
            End Get
            Set
                Me.claveSistemaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDModulo() As Integer
            Get
                Return Me.iDModuloField
            End Get
            Set
                Me.iDModuloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ApellidosyNombresCoincidencia
        
        Private numeroDNIField As String
        
        Private caracterVerificacionField As String
        
        Private tipoFichaRegistralField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private preNombresField As String
        
        Private datosField As String
        
        Private imagenField As String
        
        Private reservadoField As String
        
        '''<remarks/>
        Public Property NumeroDNI() As String
            Get
                Return Me.numeroDNIField
            End Get
            Set
                Me.numeroDNIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CaracterVerificacion() As String
            Get
                Return Me.caracterVerificacionField
            End Get
            Set
                Me.caracterVerificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoFichaRegistral() As String
            Get
                Return Me.tipoFichaRegistralField
            End Get
            Set
                Me.tipoFichaRegistralField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreNombres() As String
            Get
                Return Me.preNombresField
            End Get
            Set
                Me.preNombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Datos() As String
            Get
                Return Me.datosField
            End Get
            Set
                Me.datosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imagen() As String
            Get
                Return Me.imagenField
            End Get
            Set
                Me.imagenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reservado() As String
            Get
                Return Me.reservadoField
            End Get
            Set
                Me.reservadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ApellidosyNombres
        
        Private codigoErrorField As String
        
        Private codigoErrorMensajeField As String
        
        Private numeroTotalCoincidenciasField As String
        
        Private reservadoField As String
        
        Private coincidenciaField() As ApellidosyNombresCoincidencia
        
        Private codigoErrorClaseField As String
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        Public Property CodigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoErrorMensaje() As String
            Get
                Return Me.codigoErrorMensajeField
            End Get
            Set
                Me.codigoErrorMensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroTotalCoincidencias() As String
            Get
                Return Me.numeroTotalCoincidenciasField
            End Get
            Set
                Me.numeroTotalCoincidenciasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reservado() As String
            Get
                Return Me.reservadoField
            End Get
            Set
                Me.reservadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Coincidencia() As ApellidosyNombresCoincidencia()
            Get
                Return Me.coincidenciaField
            End Get
            Set
                Me.coincidenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoErrorClase() As String
            Get
                Return Me.codigoErrorClaseField
            End Get
            Set
                Me.codigoErrorClaseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfApellidosyNombres
        
        Private resultadoField As ApellidosyNombres
        
        Private error_CodField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As ApellidosyNombres
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Cod() As Integer
            Get
                Return Me.error_CodField
            End Get
            Set
                Me.error_CodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class NumeroDocumento
        
        Private numeroDNIField As String
        
        Private digitoVerificacionField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private apellidoCasadaField As String
        
        Private nombresField As String
        
        Private codigoUbigeoDepartamentoDomicilioField As String
        
        Private codigoUbigeoProvinciaDomicilioField As String
        
        Private codigoUbigeoDistritoDomicilioField As String
        
        Private departamentoDomicilioField As String
        
        Private provinciaDomicilioField As String
        
        Private distritoDomicilioField As String
        
        Private estadoCivilField As String
        
        Private codigoGradoInstruccionField As String
        
        Private estaturaField As String
        
        Private sexoField As String
        
        Private documentoSustentatorioTipoField As String
        
        Private documentoSustentatorioNumeroField As String
        
        Private codigoUbigeoDepartamentoNacimientoField As String
        
        Private codigoUbigeoProvinciaNacimientoField As String
        
        Private codigoUbigeoDistritoNacimientoField As String
        
        Private departamentoNacimientoField As String
        
        Private provinciaNacimientoField As String
        
        Private distritoNacimientoField As String
        
        Private fechaNacimientoField As String
        
        Private nombrePadreField As String
        
        Private nombreMadreField As String
        
        Private fechaInscripcionField As String
        
        Private fechaExpedicionField As String
        
        Private constanciaVotacionField As String
        
        Private restriccionField As String
        
        Private restriccionMensajeField As String
        
        Private prefijoDireccionField As String
        
        Private direccionField As String
        
        Private numeroDireccionField As String
        
        Private blockChaletField As String
        
        Private interiorField As String
        
        Private urbanizacionField As String
        
        Private etapaField As String
        
        Private manzanaField As String
        
        Private loteField As String
        
        Private prefijoBlockChaletField As String
        
        Private prefijoDepartamentoInteriorField As String
        
        Private prefijoUrbanizacionField As String
        
        Private fotoByteField() As Byte
        
        Private firmaByteField() As Byte
        
        Private restriccionRegistroPenitenciarioField As Boolean
        
        Private restriccionAntecedentesJudicialesField As Boolean
        
        Private restriccionTratamientoPenitenciarioField As Boolean
        
        Private restriccionMedioLibreField As Boolean
        
        '''<remarks/>
        Public Property NumeroDNI() As String
            Get
                Return Me.numeroDNIField
            End Get
            Set
                Me.numeroDNIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DigitoVerificacion() As String
            Get
                Return Me.digitoVerificacionField
            End Get
            Set
                Me.digitoVerificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApellidoCasada() As String
            Get
                Return Me.apellidoCasadaField
            End Get
            Set
                Me.apellidoCasadaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombres() As String
            Get
                Return Me.nombresField
            End Get
            Set
                Me.nombresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoDepartamentoDomicilio() As String
            Get
                Return Me.codigoUbigeoDepartamentoDomicilioField
            End Get
            Set
                Me.codigoUbigeoDepartamentoDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoProvinciaDomicilio() As String
            Get
                Return Me.codigoUbigeoProvinciaDomicilioField
            End Get
            Set
                Me.codigoUbigeoProvinciaDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoDistritoDomicilio() As String
            Get
                Return Me.codigoUbigeoDistritoDomicilioField
            End Get
            Set
                Me.codigoUbigeoDistritoDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DepartamentoDomicilio() As String
            Get
                Return Me.departamentoDomicilioField
            End Get
            Set
                Me.departamentoDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProvinciaDomicilio() As String
            Get
                Return Me.provinciaDomicilioField
            End Get
            Set
                Me.provinciaDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistritoDomicilio() As String
            Get
                Return Me.distritoDomicilioField
            End Get
            Set
                Me.distritoDomicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstadoCivil() As String
            Get
                Return Me.estadoCivilField
            End Get
            Set
                Me.estadoCivilField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoGradoInstruccion() As String
            Get
                Return Me.codigoGradoInstruccionField
            End Get
            Set
                Me.codigoGradoInstruccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estatura() As String
            Get
                Return Me.estaturaField
            End Get
            Set
                Me.estaturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocumentoSustentatorioTipo() As String
            Get
                Return Me.documentoSustentatorioTipoField
            End Get
            Set
                Me.documentoSustentatorioTipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocumentoSustentatorioNumero() As String
            Get
                Return Me.documentoSustentatorioNumeroField
            End Get
            Set
                Me.documentoSustentatorioNumeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoDepartamentoNacimiento() As String
            Get
                Return Me.codigoUbigeoDepartamentoNacimientoField
            End Get
            Set
                Me.codigoUbigeoDepartamentoNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoProvinciaNacimiento() As String
            Get
                Return Me.codigoUbigeoProvinciaNacimientoField
            End Get
            Set
                Me.codigoUbigeoProvinciaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUbigeoDistritoNacimiento() As String
            Get
                Return Me.codigoUbigeoDistritoNacimientoField
            End Get
            Set
                Me.codigoUbigeoDistritoNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DepartamentoNacimiento() As String
            Get
                Return Me.departamentoNacimientoField
            End Get
            Set
                Me.departamentoNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProvinciaNacimiento() As String
            Get
                Return Me.provinciaNacimientoField
            End Get
            Set
                Me.provinciaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistritoNacimiento() As String
            Get
                Return Me.distritoNacimientoField
            End Get
            Set
                Me.distritoNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaNacimiento() As String
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombrePadre() As String
            Get
                Return Me.nombrePadreField
            End Get
            Set
                Me.nombrePadreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreMadre() As String
            Get
                Return Me.nombreMadreField
            End Get
            Set
                Me.nombreMadreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInscripcion() As String
            Get
                Return Me.fechaInscripcionField
            End Get
            Set
                Me.fechaInscripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaExpedicion() As String
            Get
                Return Me.fechaExpedicionField
            End Get
            Set
                Me.fechaExpedicionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConstanciaVotacion() As String
            Get
                Return Me.constanciaVotacionField
            End Get
            Set
                Me.constanciaVotacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Restriccion() As String
            Get
                Return Me.restriccionField
            End Get
            Set
                Me.restriccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RestriccionMensaje() As String
            Get
                Return Me.restriccionMensajeField
            End Get
            Set
                Me.restriccionMensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrefijoDireccion() As String
            Get
                Return Me.prefijoDireccionField
            End Get
            Set
                Me.prefijoDireccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDireccion() As String
            Get
                Return Me.numeroDireccionField
            End Get
            Set
                Me.numeroDireccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BlockChalet() As String
            Get
                Return Me.blockChaletField
            End Get
            Set
                Me.blockChaletField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Interior() As String
            Get
                Return Me.interiorField
            End Get
            Set
                Me.interiorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Urbanizacion() As String
            Get
                Return Me.urbanizacionField
            End Get
            Set
                Me.urbanizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Etapa() As String
            Get
                Return Me.etapaField
            End Get
            Set
                Me.etapaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Manzana() As String
            Get
                Return Me.manzanaField
            End Get
            Set
                Me.manzanaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lote() As String
            Get
                Return Me.loteField
            End Get
            Set
                Me.loteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrefijoBlockChalet() As String
            Get
                Return Me.prefijoBlockChaletField
            End Get
            Set
                Me.prefijoBlockChaletField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrefijoDepartamentoInterior() As String
            Get
                Return Me.prefijoDepartamentoInteriorField
            End Get
            Set
                Me.prefijoDepartamentoInteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrefijoUrbanizacion() As String
            Get
                Return Me.prefijoUrbanizacionField
            End Get
            Set
                Me.prefijoUrbanizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FotoByte() As Byte()
            Get
                Return Me.fotoByteField
            End Get
            Set
                Me.fotoByteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FirmaByte() As Byte()
            Get
                Return Me.firmaByteField
            End Get
            Set
                Me.firmaByteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RestriccionRegistroPenitenciario() As Boolean
            Get
                Return Me.restriccionRegistroPenitenciarioField
            End Get
            Set
                Me.restriccionRegistroPenitenciarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RestriccionAntecedentesJudiciales() As Boolean
            Get
                Return Me.restriccionAntecedentesJudicialesField
            End Get
            Set
                Me.restriccionAntecedentesJudicialesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RestriccionTratamientoPenitenciario() As Boolean
            Get
                Return Me.restriccionTratamientoPenitenciarioField
            End Get
            Set
                Me.restriccionTratamientoPenitenciarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RestriccionMedioLibre() As Boolean
            Get
                Return Me.restriccionMedioLibreField
            End Get
            Set
                Me.restriccionMedioLibreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfNumeroDocumento
        
        Private resultadoField As NumeroDocumento
        
        Private error_CodField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As NumeroDocumento
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Cod() As Integer
            Get
                Return Me.error_CodField
            End Get
            Set
                Me.error_CodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LeerCola
        
        Private iDSolicitudField As Long
        
        Private iDColaField As Long
        
        Private loginField As String
        
        Private mACField As String
        
        Private ipField As String
        
        Private iDModuloField As Integer
        
        '''<remarks/>
        Public Property IDSolicitud() As Long
            Get
                Return Me.iDSolicitudField
            End Get
            Set
                Me.iDSolicitudField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDCola() As Long
            Get
                Return Me.iDColaField
            End Get
            Set
                Me.iDColaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Login() As String
            Get
                Return Me.loginField
            End Get
            Set
                Me.loginField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MAC() As String
            Get
                Return Me.mACField
            End Get
            Set
                Me.mACField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IP() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDModulo() As Integer
            Get
                Return Me.iDModuloField
            End Get
            Set
                Me.iDModuloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Respuesta
        
        Private iDSolicitudField As Long
        
        Private iDColaField As Long
        
        '''<remarks/>
        Public Property IDSolicitud() As Long
            Get
                Return Me.iDSolicitudField
            End Get
            Set
                Me.iDSolicitudField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDCola() As Long
            Get
                Return Me.iDColaField
            End Get
            Set
                Me.iDColaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfRespuesta
        
        Private resultadoField As Respuesta
        
        Private error_CodField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As Respuesta
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Cod() As Integer
            Get
                Return Me.error_CodField
            End Get
            Set
                Me.error_CodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub VersionCompletedEventHandler(ByVal sender As Object, ByVal e As VersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub FechaLongCompletedEventHandler(ByVal sender As Object, ByVal e As FechaLongCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FechaLongCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SolicitudCompletedEventHandler(ByVal sender As Object, ByVal e As SolicitudCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SolicitudCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfRespuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfRespuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Solicitud_LeerDNICompletedEventHandler(ByVal sender As Object, ByVal e As Solicitud_LeerDNICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Solicitud_LeerDNICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfNumeroDocumento
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfNumeroDocumento)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Solicitud_LeerApellidosyNombresCompletedEventHandler(ByVal sender As Object, ByVal e As Solicitud_LeerApellidosyNombresCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Solicitud_LeerApellidosyNombresCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfApellidosyNombres
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfApellidosyNombres)
            End Get
        End Property
    End Class
End Namespace
