'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ws_pope_sede_plm_carceleta
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CarceletaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Carceleta
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ListarDataZXPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarDocumentosZXPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmarDescargaDataZXPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmarDescargaDocumentosZXPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarDatIntOtrosZXPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListaPendRecepTrasladoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarDetPaqueteEPLimMetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfirmarRecepTrasladoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarDetPaqIntEPProvOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarDatBasicoInternoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListarInterno_Para_LimaProvinciasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private _testOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.APPWebService.My.MySettings.Default.APPWebService_ws_pope_sede_plm_carceleta_Carceleta
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ListarDataZXPCompleted As ListarDataZXPCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarDocumentosZXPCompleted As ListarDocumentosZXPCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmarDescargaDataZXPCompleted As ConfirmarDescargaDataZXPCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmarDescargaDocumentosZXPCompleted As ConfirmarDescargaDocumentosZXPCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarDatIntOtrosZXPCompleted As ListarDatIntOtrosZXPCompletedEventHandler
        
        '''<remarks/>
        Public Event ListaPendRecepTrasladoCompleted As ListaPendRecepTrasladoCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarDetPaqueteEPLimMetCompleted As ListarDetPaqueteEPLimMetCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfirmarRecepTrasladoCompleted As ConfirmarRecepTrasladoCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarDetPaqIntEPProvCompleted As ListarDetPaqIntEPProvCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarDatBasicoInternoCompleted As ListarDatBasicoInternoCompletedEventHandler
        
        '''<remarks/>
        Public Event ListarInterno_Para_LimaProvinciasCompleted As ListarInterno_Para_LimaProvinciasCompletedEventHandler
        
        '''<remarks/>
        Public Event _testCompleted As _testCompletedEventHandler
        
        '''<remarks/>
        Public Event getVersionCompleted As getVersionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDataZXP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDataZXP(ByVal internoSedeId As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDataZXP", New Object() {internoSedeId})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDataZXPAsync(ByVal internoSedeId As Integer)
            Me.ListarDataZXPAsync(internoSedeId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDataZXPAsync(ByVal internoSedeId As Integer, ByVal userState As Object)
            If (Me.ListarDataZXPOperationCompleted Is Nothing) Then
                Me.ListarDataZXPOperationCompleted = AddressOf Me.OnListarDataZXPOperationCompleted
            End If
            Me.InvokeAsync("ListarDataZXP", New Object() {internoSedeId}, Me.ListarDataZXPOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDataZXPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDataZXPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDataZXPCompleted(Me, New ListarDataZXPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDocumentosZXP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDocumentosZXP(ByVal internoSedeId As Integer, ByVal PenId As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDocumentosZXP", New Object() {internoSedeId, PenId})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDocumentosZXPAsync(ByVal internoSedeId As Integer, ByVal PenId As Integer)
            Me.ListarDocumentosZXPAsync(internoSedeId, PenId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDocumentosZXPAsync(ByVal internoSedeId As Integer, ByVal PenId As Integer, ByVal userState As Object)
            If (Me.ListarDocumentosZXPOperationCompleted Is Nothing) Then
                Me.ListarDocumentosZXPOperationCompleted = AddressOf Me.OnListarDocumentosZXPOperationCompleted
            End If
            Me.InvokeAsync("ListarDocumentosZXP", New Object() {internoSedeId, PenId}, Me.ListarDocumentosZXPOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDocumentosZXPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDocumentosZXPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDocumentosZXPCompleted(Me, New ListarDocumentosZXPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarDescargaDataZXP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarDescargaDataZXP(ByVal dat As System.Data.DataSet) As DTO_ResultOfBoolean
            Dim results() As Object = Me.Invoke("ConfirmarDescargaDataZXP", New Object() {dat})
            Return CType(results(0),DTO_ResultOfBoolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmarDescargaDataZXPAsync(ByVal dat As System.Data.DataSet)
            Me.ConfirmarDescargaDataZXPAsync(dat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmarDescargaDataZXPAsync(ByVal dat As System.Data.DataSet, ByVal userState As Object)
            If (Me.ConfirmarDescargaDataZXPOperationCompleted Is Nothing) Then
                Me.ConfirmarDescargaDataZXPOperationCompleted = AddressOf Me.OnConfirmarDescargaDataZXPOperationCompleted
            End If
            Me.InvokeAsync("ConfirmarDescargaDataZXP", New Object() {dat}, Me.ConfirmarDescargaDataZXPOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmarDescargaDataZXPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmarDescargaDataZXPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmarDescargaDataZXPCompleted(Me, New ConfirmarDescargaDataZXPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarDescargaDocumentosZXP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarDescargaDocumentosZXP(ByVal dat As System.Data.DataSet) As DTO_ResultOfBoolean
            Dim results() As Object = Me.Invoke("ConfirmarDescargaDocumentosZXP", New Object() {dat})
            Return CType(results(0),DTO_ResultOfBoolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmarDescargaDocumentosZXPAsync(ByVal dat As System.Data.DataSet)
            Me.ConfirmarDescargaDocumentosZXPAsync(dat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmarDescargaDocumentosZXPAsync(ByVal dat As System.Data.DataSet, ByVal userState As Object)
            If (Me.ConfirmarDescargaDocumentosZXPOperationCompleted Is Nothing) Then
                Me.ConfirmarDescargaDocumentosZXPOperationCompleted = AddressOf Me.OnConfirmarDescargaDocumentosZXPOperationCompleted
            End If
            Me.InvokeAsync("ConfirmarDescargaDocumentosZXP", New Object() {dat}, Me.ConfirmarDescargaDocumentosZXPOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmarDescargaDocumentosZXPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmarDescargaDocumentosZXPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmarDescargaDocumentosZXPCompleted(Me, New ConfirmarDescargaDocumentosZXPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDatIntOtrosZXP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDatIntOtrosZXP(ByVal IngInpId As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDatIntOtrosZXP", New Object() {IngInpId})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDatIntOtrosZXPAsync(ByVal IngInpId As Integer)
            Me.ListarDatIntOtrosZXPAsync(IngInpId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDatIntOtrosZXPAsync(ByVal IngInpId As Integer, ByVal userState As Object)
            If (Me.ListarDatIntOtrosZXPOperationCompleted Is Nothing) Then
                Me.ListarDatIntOtrosZXPOperationCompleted = AddressOf Me.OnListarDatIntOtrosZXPOperationCompleted
            End If
            Me.InvokeAsync("ListarDatIntOtrosZXP", New Object() {IngInpId}, Me.ListarDatIntOtrosZXPOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDatIntOtrosZXPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDatIntOtrosZXPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDatIntOtrosZXPCompleted(Me, New ListarDatIntOtrosZXPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaPendRecepTraslado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListaPendRecepTraslado(ByVal pen_id As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ListaPendRecepTraslado", New Object() {pen_id})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListaPendRecepTrasladoAsync(ByVal pen_id As Integer)
            Me.ListaPendRecepTrasladoAsync(pen_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListaPendRecepTrasladoAsync(ByVal pen_id As Integer, ByVal userState As Object)
            If (Me.ListaPendRecepTrasladoOperationCompleted Is Nothing) Then
                Me.ListaPendRecepTrasladoOperationCompleted = AddressOf Me.OnListaPendRecepTrasladoOperationCompleted
            End If
            Me.InvokeAsync("ListaPendRecepTraslado", New Object() {pen_id}, Me.ListaPendRecepTrasladoOperationCompleted, userState)
        End Sub
        
        Private Sub OnListaPendRecepTrasladoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaPendRecepTrasladoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaPendRecepTrasladoCompleted(Me, New ListaPendRecepTrasladoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDetPaqueteEPLimMet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDetPaqueteEPLimMet(ByVal int_id As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDetPaqueteEPLimMet", New Object() {int_id})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDetPaqueteEPLimMetAsync(ByVal int_id As Integer)
            Me.ListarDetPaqueteEPLimMetAsync(int_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDetPaqueteEPLimMetAsync(ByVal int_id As Integer, ByVal userState As Object)
            If (Me.ListarDetPaqueteEPLimMetOperationCompleted Is Nothing) Then
                Me.ListarDetPaqueteEPLimMetOperationCompleted = AddressOf Me.OnListarDetPaqueteEPLimMetOperationCompleted
            End If
            Me.InvokeAsync("ListarDetPaqueteEPLimMet", New Object() {int_id}, Me.ListarDetPaqueteEPLimMetOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDetPaqueteEPLimMetOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDetPaqueteEPLimMetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDetPaqueteEPLimMetCompleted(Me, New ListarDetPaqueteEPLimMetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarRecepTraslado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarRecepTraslado(ByVal internoIdSede As Integer, ByVal mov_trs_id As Integer) As Integer
            Dim results() As Object = Me.Invoke("ConfirmarRecepTraslado", New Object() {internoIdSede, mov_trs_id})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfirmarRecepTrasladoAsync(ByVal internoIdSede As Integer, ByVal mov_trs_id As Integer)
            Me.ConfirmarRecepTrasladoAsync(internoIdSede, mov_trs_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfirmarRecepTrasladoAsync(ByVal internoIdSede As Integer, ByVal mov_trs_id As Integer, ByVal userState As Object)
            If (Me.ConfirmarRecepTrasladoOperationCompleted Is Nothing) Then
                Me.ConfirmarRecepTrasladoOperationCompleted = AddressOf Me.OnConfirmarRecepTrasladoOperationCompleted
            End If
            Me.InvokeAsync("ConfirmarRecepTraslado", New Object() {internoIdSede, mov_trs_id}, Me.ConfirmarRecepTrasladoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfirmarRecepTrasladoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConfirmarRecepTrasladoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfirmarRecepTrasladoCompleted(Me, New ConfirmarRecepTrasladoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDetPaqIntEPProv", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDetPaqIntEPProv(ByVal int_id As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDetPaqIntEPProv", New Object() {int_id})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDetPaqIntEPProvAsync(ByVal int_id As Integer)
            Me.ListarDetPaqIntEPProvAsync(int_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDetPaqIntEPProvAsync(ByVal int_id As Integer, ByVal userState As Object)
            If (Me.ListarDetPaqIntEPProvOperationCompleted Is Nothing) Then
                Me.ListarDetPaqIntEPProvOperationCompleted = AddressOf Me.OnListarDetPaqIntEPProvOperationCompleted
            End If
            Me.InvokeAsync("ListarDetPaqIntEPProv", New Object() {int_id}, Me.ListarDetPaqIntEPProvOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDetPaqIntEPProvOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDetPaqIntEPProvCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDetPaqIntEPProvCompleted(Me, New ListarDetPaqIntEPProvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDatBasicoInterno", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarDatBasicoInterno(ByVal int_id As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarDatBasicoInterno", New Object() {int_id})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarDatBasicoInternoAsync(ByVal int_id As Integer)
            Me.ListarDatBasicoInternoAsync(int_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarDatBasicoInternoAsync(ByVal int_id As Integer, ByVal userState As Object)
            If (Me.ListarDatBasicoInternoOperationCompleted Is Nothing) Then
                Me.ListarDatBasicoInternoOperationCompleted = AddressOf Me.OnListarDatBasicoInternoOperationCompleted
            End If
            Me.InvokeAsync("ListarDatBasicoInterno", New Object() {int_id}, Me.ListarDatBasicoInternoOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarDatBasicoInternoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarDatBasicoInternoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarDatBasicoInternoCompleted(Me, New ListarDatBasicoInternoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarInterno_Para_LimaProvincias", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListarInterno_Para_LimaProvincias(ByVal intIDInterno As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ListarInterno_Para_LimaProvincias", New Object() {intIDInterno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListarInterno_Para_LimaProvinciasAsync(ByVal intIDInterno As Integer)
            Me.ListarInterno_Para_LimaProvinciasAsync(intIDInterno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListarInterno_Para_LimaProvinciasAsync(ByVal intIDInterno As Integer, ByVal userState As Object)
            If (Me.ListarInterno_Para_LimaProvinciasOperationCompleted Is Nothing) Then
                Me.ListarInterno_Para_LimaProvinciasOperationCompleted = AddressOf Me.OnListarInterno_Para_LimaProvinciasOperationCompleted
            End If
            Me.InvokeAsync("ListarInterno_Para_LimaProvincias", New Object() {intIDInterno}, Me.ListarInterno_Para_LimaProvinciasOperationCompleted, userState)
        End Sub
        
        Private Sub OnListarInterno_Para_LimaProvinciasOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListarInterno_Para_LimaProvinciasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListarInterno_Para_LimaProvinciasCompleted(Me, New ListarInterno_Para_LimaProvinciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function _test() As Long
            Dim results() As Object = Me.Invoke("_test", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub _testAsync()
            Me._testAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub _testAsync(ByVal userState As Object)
            If (Me._testOperationCompleted Is Nothing) Then
                Me._testOperationCompleted = AddressOf Me.On_testOperationCompleted
            End If
            Me.InvokeAsync("_test", New Object(-1) {}, Me._testOperationCompleted, userState)
        End Sub
        
        Private Sub On_testOperationCompleted(ByVal arg As Object)
            If (Not (Me._testCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent _testCompleted(Me, New _testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getVersion() As String
            Dim results() As Object = Me.Invoke("getVersion", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getVersionAsync()
            Me.getVersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getVersionAsync(ByVal userState As Object)
            If (Me.getVersionOperationCompleted Is Nothing) Then
                Me.getVersionOperationCompleted = AddressOf Me.OngetVersionOperationCompleted
            End If
            Me.InvokeAsync("getVersion", New Object(-1) {}, Me.getVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OngetVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.getVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getVersionCompleted(Me, New getVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTO_ResultOfBoolean
        
        Private resultadoField As Boolean
        
        Private error_codField As Integer
        
        Private error_MensajeField As String
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_cod() As Integer
            Get
                Return Me.error_codField
            End Get
            Set
                Me.error_codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Mensaje() As String
            Get
                Return Me.error_MensajeField
            End Get
            Set
                Me.error_MensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDataZXPCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDataZXPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDataZXPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDocumentosZXPCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDocumentosZXPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDocumentosZXPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConfirmarDescargaDataZXPCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmarDescargaDataZXPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmarDescargaDataZXPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfBoolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfBoolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConfirmarDescargaDocumentosZXPCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmarDescargaDocumentosZXPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmarDescargaDocumentosZXPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DTO_ResultOfBoolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DTO_ResultOfBoolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDatIntOtrosZXPCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDatIntOtrosZXPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDatIntOtrosZXPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListaPendRecepTrasladoCompletedEventHandler(ByVal sender As Object, ByVal e As ListaPendRecepTrasladoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListaPendRecepTrasladoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDetPaqueteEPLimMetCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDetPaqueteEPLimMetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDetPaqueteEPLimMetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConfirmarRecepTrasladoCompletedEventHandler(ByVal sender As Object, ByVal e As ConfirmarRecepTrasladoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfirmarRecepTrasladoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDetPaqIntEPProvCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDetPaqIntEPProvCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDetPaqIntEPProvCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarDatBasicoInternoCompletedEventHandler(ByVal sender As Object, ByVal e As ListarDatBasicoInternoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarDatBasicoInternoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListarInterno_Para_LimaProvinciasCompletedEventHandler(ByVal sender As Object, ByVal e As ListarInterno_Para_LimaProvinciasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListarInterno_Para_LimaProvinciasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub _testCompletedEventHandler(ByVal sender As Object, ByVal e As _testCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class _testCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getVersionCompletedEventHandler(ByVal sender As Object, ByVal e As getVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
