'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ws_pope_sede_monitoreo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MonitoreoSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Monitoreo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private FechaActualOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListaPendiente_RegionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListaPendiente_DetalleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListaArchivoTransferenciaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EliminarArchivoTransferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DescargarZipArchivoTransferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.APPWebService.My.MySettings.Default.APPWebService_ws_pope_sede_monitoreo_Monitoreo
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event FechaActualCompleted As FechaActualCompletedEventHandler
        
        '''<remarks/>
        Public Event VersionCompleted As VersionCompletedEventHandler
        
        '''<remarks/>
        Public Event ListaPendiente_RegionCompleted As ListaPendiente_RegionCompletedEventHandler
        
        '''<remarks/>
        Public Event ListaPendiente_DetalleCompleted As ListaPendiente_DetalleCompletedEventHandler
        
        '''<remarks/>
        Public Event ListaArchivoTransferenciaCompleted As ListaArchivoTransferenciaCompletedEventHandler
        
        '''<remarks/>
        Public Event EliminarArchivoTransferCompleted As EliminarArchivoTransferCompletedEventHandler
        
        '''<remarks/>
        Public Event DescargarZipArchivoTransferCompleted As DescargarZipArchivoTransferCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechaActual", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FechaActual() As Long
            Dim results() As Object = Me.Invoke("FechaActual", New Object(-1) {})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FechaActualAsync()
            Me.FechaActualAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FechaActualAsync(ByVal userState As Object)
            If (Me.FechaActualOperationCompleted Is Nothing) Then
                Me.FechaActualOperationCompleted = AddressOf Me.OnFechaActualOperationCompleted
            End If
            Me.InvokeAsync("FechaActual", New Object(-1) {}, Me.FechaActualOperationCompleted, userState)
        End Sub
        
        Private Sub OnFechaActualOperationCompleted(ByVal arg As Object)
            If (Not (Me.FechaActualCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FechaActualCompleted(Me, New FechaActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Version() As String
            Dim results() As Object = Me.Invoke("Version", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VersionAsync()
            Me.VersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VersionAsync(ByVal userState As Object)
            If (Me.VersionOperationCompleted Is Nothing) Then
                Me.VersionOperationCompleted = AddressOf Me.OnVersionOperationCompleted
            End If
            Me.InvokeAsync("Version", New Object(-1) {}, Me.VersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.VersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VersionCompleted(Me, New VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaPendiente_Region", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListaPendiente_Region(ByVal RegionID As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ListaPendiente_Region", New Object() {RegionID})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListaPendiente_RegionAsync(ByVal RegionID As Integer)
            Me.ListaPendiente_RegionAsync(RegionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListaPendiente_RegionAsync(ByVal RegionID As Integer, ByVal userState As Object)
            If (Me.ListaPendiente_RegionOperationCompleted Is Nothing) Then
                Me.ListaPendiente_RegionOperationCompleted = AddressOf Me.OnListaPendiente_RegionOperationCompleted
            End If
            Me.InvokeAsync("ListaPendiente_Region", New Object() {RegionID}, Me.ListaPendiente_RegionOperationCompleted, userState)
        End Sub
        
        Private Sub OnListaPendiente_RegionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaPendiente_RegionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaPendiente_RegionCompleted(Me, New ListaPendiente_RegionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaPendiente_Detalle", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListaPendiente_Detalle(ByVal RegionID As Integer, ByVal PenalID As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ListaPendiente_Detalle", New Object() {RegionID, PenalID})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListaPendiente_DetalleAsync(ByVal RegionID As Integer, ByVal PenalID As Integer)
            Me.ListaPendiente_DetalleAsync(RegionID, PenalID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListaPendiente_DetalleAsync(ByVal RegionID As Integer, ByVal PenalID As Integer, ByVal userState As Object)
            If (Me.ListaPendiente_DetalleOperationCompleted Is Nothing) Then
                Me.ListaPendiente_DetalleOperationCompleted = AddressOf Me.OnListaPendiente_DetalleOperationCompleted
            End If
            Me.InvokeAsync("ListaPendiente_Detalle", New Object() {RegionID, PenalID}, Me.ListaPendiente_DetalleOperationCompleted, userState)
        End Sub
        
        Private Sub OnListaPendiente_DetalleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaPendiente_DetalleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaPendiente_DetalleCompleted(Me, New ListaPendiente_DetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaArchivoTransferencia", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListaArchivoTransferencia(ByVal Codigo As Integer, ByVal RegionID As Integer, ByVal PenalID As Integer, ByVal anioDirectorio As Integer, ByVal numMesRegistro As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ListaArchivoTransferencia", New Object() {Codigo, RegionID, PenalID, anioDirectorio, numMesRegistro})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListaArchivoTransferenciaAsync(ByVal Codigo As Integer, ByVal RegionID As Integer, ByVal PenalID As Integer, ByVal anioDirectorio As Integer, ByVal numMesRegistro As Integer)
            Me.ListaArchivoTransferenciaAsync(Codigo, RegionID, PenalID, anioDirectorio, numMesRegistro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListaArchivoTransferenciaAsync(ByVal Codigo As Integer, ByVal RegionID As Integer, ByVal PenalID As Integer, ByVal anioDirectorio As Integer, ByVal numMesRegistro As Integer, ByVal userState As Object)
            If (Me.ListaArchivoTransferenciaOperationCompleted Is Nothing) Then
                Me.ListaArchivoTransferenciaOperationCompleted = AddressOf Me.OnListaArchivoTransferenciaOperationCompleted
            End If
            Me.InvokeAsync("ListaArchivoTransferencia", New Object() {Codigo, RegionID, PenalID, anioDirectorio, numMesRegistro}, Me.ListaArchivoTransferenciaOperationCompleted, userState)
        End Sub
        
        Private Sub OnListaArchivoTransferenciaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaArchivoTransferenciaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaArchivoTransferenciaCompleted(Me, New ListaArchivoTransferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarArchivoTransfer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EliminarArchivoTransfer(ByVal intCodigo As Integer, ByVal strNombreArchivo As String, ByVal intGrupoPaquete As Short) As Boolean
            Dim results() As Object = Me.Invoke("EliminarArchivoTransfer", New Object() {intCodigo, strNombreArchivo, intGrupoPaquete})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EliminarArchivoTransferAsync(ByVal intCodigo As Integer, ByVal strNombreArchivo As String, ByVal intGrupoPaquete As Short)
            Me.EliminarArchivoTransferAsync(intCodigo, strNombreArchivo, intGrupoPaquete, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminarArchivoTransferAsync(ByVal intCodigo As Integer, ByVal strNombreArchivo As String, ByVal intGrupoPaquete As Short, ByVal userState As Object)
            If (Me.EliminarArchivoTransferOperationCompleted Is Nothing) Then
                Me.EliminarArchivoTransferOperationCompleted = AddressOf Me.OnEliminarArchivoTransferOperationCompleted
            End If
            Me.InvokeAsync("EliminarArchivoTransfer", New Object() {intCodigo, strNombreArchivo, intGrupoPaquete}, Me.EliminarArchivoTransferOperationCompleted, userState)
        End Sub
        
        Private Sub OnEliminarArchivoTransferOperationCompleted(ByVal arg As Object)
            If (Not (Me.EliminarArchivoTransferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EliminarArchivoTransferCompleted(Me, New EliminarArchivoTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DescargarZipArchivoTransfer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DescargarZipArchivoTransfer(ByVal intCodigo As Integer, ByVal strNombreArchivo As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("DescargarZipArchivoTransfer", New Object() {intCodigo, strNombreArchivo})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DescargarZipArchivoTransferAsync(ByVal intCodigo As Integer, ByVal strNombreArchivo As String)
            Me.DescargarZipArchivoTransferAsync(intCodigo, strNombreArchivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DescargarZipArchivoTransferAsync(ByVal intCodigo As Integer, ByVal strNombreArchivo As String, ByVal userState As Object)
            If (Me.DescargarZipArchivoTransferOperationCompleted Is Nothing) Then
                Me.DescargarZipArchivoTransferOperationCompleted = AddressOf Me.OnDescargarZipArchivoTransferOperationCompleted
            End If
            Me.InvokeAsync("DescargarZipArchivoTransfer", New Object() {intCodigo, strNombreArchivo}, Me.DescargarZipArchivoTransferOperationCompleted, userState)
        End Sub
        
        Private Sub OnDescargarZipArchivoTransferOperationCompleted(ByVal arg As Object)
            If (Not (Me.DescargarZipArchivoTransferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DescargarZipArchivoTransferCompleted(Me, New DescargarZipArchivoTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub FechaActualCompletedEventHandler(ByVal sender As Object, ByVal e As FechaActualCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FechaActualCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub VersionCompletedEventHandler(ByVal sender As Object, ByVal e As VersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListaPendiente_RegionCompletedEventHandler(ByVal sender As Object, ByVal e As ListaPendiente_RegionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListaPendiente_RegionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListaPendiente_DetalleCompletedEventHandler(ByVal sender As Object, ByVal e As ListaPendiente_DetalleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListaPendiente_DetalleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListaArchivoTransferenciaCompletedEventHandler(ByVal sender As Object, ByVal e As ListaArchivoTransferenciaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListaArchivoTransferenciaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EliminarArchivoTransferCompletedEventHandler(ByVal sender As Object, ByVal e As EliminarArchivoTransferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EliminarArchivoTransferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DescargarZipArchivoTransferCompletedEventHandler(ByVal sender As Object, ByVal e As DescargarZipArchivoTransferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DescargarZipArchivoTransferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
End Namespace
