'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/sip/multimedia_local_lurigancho/PopeLocal.asmx")>  _
        Public ReadOnly Property APPWebService_ws_foto_UploadFile() As String
            Get
                Return CType(Me("APPWebService_ws_foto_UploadFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://srvdesappall:8090/sip/SedeCentral/TransferenciaSIP/Monitoreo.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_monitoreo_Monitoreo() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_monitoreo_Monitoreo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/POPE/Sede/TablaMaestras.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_tp_TablaParametrica() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_tp_TablaParametrica"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsdev.inpe.gob.pe/Pope/sede/TablaMaestras_Config.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_tp_config_TablaMaestras_Config() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_tp_config_TablaMaestras_Config"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsdev.inpe.gob.pe/Pope/sede/Usuario.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_usuario_Usuario() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_usuario_Usuario"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/SIPGA/sede/Usuario.asmx")>  _
        Public ReadOnly Property APPWebService_ws_sipga_sede_usuario_Usuario() As String
            Get
                Return CType(Me("APPWebService_ws_sipga_sede_usuario_Usuario"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/Reniec/ConsultaMQ/identificacion.asmx")>  _
        Public ReadOnly Property APPWebService_ws_reniec_sede_Identificacion() As String
            Get
                Return CType(Me("APPWebService_ws_reniec_sede_Identificacion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:52145/ws_pope_sede/Padin.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_padin_Padin() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_padin_Padin"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsdev.inpe.gob.pe/Pope/sedesanciones/Sanciones.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_sanciones_WSSanciones() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_sanciones_WSSanciones"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/sipga/sede/Trabajador.asmx")>  _
        Public ReadOnly Property APPWebService_ws_sipga_sede_trabajador_Trabajador() As String
            Get
                Return CType(Me("APPWebService_ws_sipga_sede_trabajador_Trabajador"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/Pope/sedeplm/InternoCarceleta.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_plm_carceleta_Carceleta() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_plm_carceleta_Carceleta"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ws.inpe.gob.pe/SIP/SedePLM/InternoSede.asmx")>  _
        Public ReadOnly Property APPWebService_ws_pope_sede_plm_Interno_WS_InternoSede() As String
            Get
                Return CType(Me("APPWebService_ws_pope_sede_plm_Interno_WS_InternoSede"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://websvc.inpe.gob.pe/WSMigraciones/Migraciones.svc")>  _
        Public ReadOnly Property APPWebService_ws_migraciones_consulta_Service1() As String
            Get
                Return CType(Me("APPWebService_ws_migraciones_consulta_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://srvdesappall:8080/SedeCentral/SedeBiometria/VerificacionBiometrica.asmx")>  _
        Public ReadOnly Property APPWebService_ws_reniec_biometria_VerificacionBiometrica() As String
            Get
                Return CType(Me("APPWebService_ws_reniec_biometria_VerificacionBiometrica"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.APPWebService.My.MySettings
            Get
                Return Global.APPWebService.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
